# Generated by Django 3.2.9 on 2022-05-10 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ANNUAL', 'ANNUAL'), ('MONTHLY', 'MONTHLY'), ('NUMBER', 'REQUEST_NUMBER')], max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('request_number', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='media/default.png', null=True, upload_to=users.models.upload_to)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.license')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
